permalink: /posts/:year-:month-:slug/
source: site
destination: .build
livereload: true
url: "https://blog.cedernaes.com"
timezone: Europe/Stockholm
strict_front_matter: True
title: "Emaus' blogsite"

feed:
    max_posts: 10

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "_posts"
    values:
      layout: "post"
