permalink: /posts/:year-:month-:slug/
source: site
destination: docs
livereload: true
url: "https://blog.cedernaes.com"
repo: "https://github.com/emanuelen5/emanuelen5.github.io/"
email: blogsite@emaus.dev
timezone: Europe/Stockholm
strict_front_matter: True
title: "Emaus' blogsite"

feed:
    max_posts: 10

collections:
    tips:
        output: true
    recipes:
        output: true

exclude:
  - '_drafts/*.png'

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "_drafts"
    values:
      layout: "post"
  - scope:
      path: "_posts"
    values:
      layout: "post"
  - scope:
      path: "_tips"
    values:
      layout: "tip"
  - scope:
      path: "_recipes"
    values:
      layout: "recipe"
