services:
  github-pages:
    build: .
    working_dir: /app
    volumes:
      - ./site:/app/site
      - ./Gemfile:/app/Gemfile
      - ./Gemfile.lock:/app/Gemfile.lock
    ports:
      - "4000:4000"
      - "35729:35729"
    command: jekyll serve -H '0.0.0.0' -P 4000 --watch --drafts --force_polling --livereload

