name: Build site and check links with htmlproofer

on:
  push:
    branches: [blog]
  pull_request:

jobs:
  htmlproofer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3
    - name: Cache bundler dependencies
      uses: actions/cache@v4
      id: gems
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Install bundler
      run: |
        gem install bundler
        bundle config path vendor/bundle
    - name: Install bundler dependencies
      if: steps.gems.outputs.cache-hit != 'true'
      run: |
        bundle install --jobs 4 --retry 3
    - name: Build site
      run: make build
    - name: Test external links (no fail)
      run: FLAGS="--log-level=debug --external-only" make htmlproofer || true
    - name: Test internal links
      run: FLAGS="--log-level=debug --disable-external" make htmlproofer
