name: Build site and check links

on:
    push:
        branches:
            - '*'
    schedule:
        - cron: '12 0 * * 0' # Run every sunday at 12:00

env:
    BUILD_DIR: .build

jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Cache bundler dependencies
      uses: actions/cache@v1
      id: gems
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Install bundler
      run: |
        gem install bundler
        bundle config path vendor/bundle
    - name: Install bundler dependencies
      if: steps.gems.outputs.cache-hit != 'true'
      run: |
        bundle install --jobs 4 --retry 3
    - name: Test links
      run: |
        make test
