name: Build and deploy site to Github Pages

on:
  push:
    branches: [ gh-pages-deploy ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3
    - name: Cache bundler dependencies
      uses: actions/cache@v4
      id: gems
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Install bundler
      run: |
        gem install bundler
        bundle config path vendor/bundle
    - name: Install bundler dependencies
      if: steps.gems.outputs.cache-hit != 'true'
      run: |
        bundle install --jobs 4 --retry 3
    - name: Build site
      run: |
        make gh-pages
    - name: Commit and push changes
      run: |
        git config --local user.name "Github action builder"
        git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add --force docs
        git commit -m "Built site from commit $GITHUB_SHA"
        git push origin HEAD:_build --force
